### ISSUE TITLE
CubismMouthController does not work.

### ISSUE THREAD

**Issue by madnesslabo** [Live2D/CubismUnityComponents#1]
CubismMouthController does not work.
When I looked at CubismEyeBlinkController which seems to have a similar function, I found a mistake in the source code.

CubismMouthController.cs Line58
`                .GetComponentsMany<CubismMouthController>();`
This is a mistake, is not it right to write as follows?
`                .GetComponentsMany<CubismMouthParameter>();`

以下、日本語です。
CubismMouthControllerが動作しなかったため、似たような機能と思われる「CubismEyeBlinkController 」と比べてみたところ、ソースコードの間違いと思われる場所をみつけました。

CubismMouthController.cs の58行目
`                .GetComponentsMany<CubismMouthController>();`
これは間違いで、以下のように書くのが正しいのではないでしょうか。
`                .GetComponentsMany<CubismMouthParameter>();`

58行目のCubismMouthControllerをCubismMouthParameterに変えたところ動作するようになりました。
よろしくお願いします。

**Comment by andi-at-live2d-com** [comment]
Hey, thank you very much for spotting the issue, reporting it in English, and for explaining how to fix it! I just pushed the fix so I'll close this issue.
I'm always looking forward for any feedback!
