### ISSUE TITLE
Why sync vertex positions here?

### ISSUE THREAD

**Issue by qiankanglai** [Live2D/CubismUnityComponents#12]
https://github.com/Live2D/CubismUnityComponents/blob/master/Assets/Live2D/Cubism/Rendering/CubismRenderer.cs#L358

    mesh.vertices = Meshes[FrontMesh].vertices;

I don't think this is useful except one two copies. I tried comment it and add `Debug.Log`, found everything works in fact.

**Comment by itoh-at-live2d-com** [comment]
@qiankanglai 
Hi, thank you for reporting.
It is a remnant of past bug fixes.
After removing some code, it seemed that there was no problem in behavior.
I will commit the code.
