### ISSUE TITLE
Cubism Parameters Inspector does not work properly.

### ISSUE THREAD

**Issue by dobunezumi** [Live2D/CubismUnityComponents#3]
Please open a scene "Animation". 
And please move the slider "PARAM_HAND_SWITCH_L" of AnimatingKoharu quickly.
The object looks strange.

![koharu_test](https://cloud.githubusercontent.com/assets/28889185/26343728/18e9b5d8-3fd8-11e7-87f3-699d6d16993a.gif)

**Comment by ono-at-live2d-com** [comment]
@dobunezumi 

Thank you for reporting the issue.

We are checking the details and fixing this issue within a few days.
This issue only happens when parameters are operated in Inspector and won't happen by operation in the program.

**Comment by itoh-at-live2d-com** [comment]
@dobunezumi 

Thanks again for reporting the issue!
I just pushed the fix.
Sorry for taking so long.
