### ISSUE TITLE
A clipping is delayed on Unity

### ISSUE THREAD

**Issue by sasakiSG** [Live2D/CubismUnityComponents#4]
Live2D animation was changed on Unity and uneasiness was felt in movement of a blink, so it expanded, and it was checked.
A clipping makes the pupil rather white, though a white fitted into eyelashes when closing an eye quickly, pupil stuck up on the eyelashes.
When opening an eye, the upper part of a pupil broke, and a white was seen.
When blinking slowly, I don't stick out and am shown right.

A clipping can't follow a quick movement of parts, and they seem late.

**Comment by andi-at-live2d-com** [comment]
Hey, thanks for reporting the issue! Just as you assume, clipping is one frame behind... Me or @itoh-at-live2d-com will get back to you as soon as we have that issue fixed!

**Comment by itoh-at-live2d-com** [comment]
@sasakiSG

Just I fixed this issue now. To try out the fix, you can simply download [this branch](https://github.com/Live2D/CubismUnityComponents/tree/develop) as a zip and overwrite the corresponding scripts in your project.

**Comment by sasakiSG** [comment]
I overrode a defrosted file, but don't fixed.
This is an animation after application.

http://blindfold.girly.jp/secret/anim_test.zip

**Comment by andi-at-live2d-com** [comment]
@sasakiSG Thanks for giving it a try right away! Would it be possible for you to send over the Unity project or another sample Unity project that shows the error to support@live2d.com so we can reproduce the problem? The data we tried doesn't show that behavior...

**Comment by sasakiSG** [comment]
http://blindfold.girly.jp/game/Live2D test2.zip

It's a project.
And when the parts of 0 were made 100 clarity-lessly, flickering started to go out after this patch was applied.

**Comment by andi-at-live2d-com** [comment]
@sasakiSG Thanks for the project!

> And when the parts of 0 were made 100 clarity-lessly, flickering started to go out after this patch was applied.

So you changed the opacity of some parts and clipping started to work, right? I guess you already changed that in the project...

**Comment by sasakiSG** [comment]
? I don't know what you'd like to call.
Please say in easier English.

**Comment by andi-at-live2d-com** [comment]
Ah, sorry. English is also a foreign language for me...

> And when the parts of 0 were made 100 clarity-lessly, flickering started to go out after this patch was applied.

This means:

1. You applied patch.
1. You made parts 100% opaque(不透明).
1. Clipping masks are good.
1. You uploaded project.

Is that correct?

**Comment by sasakiSG** [comment]
Me, too.
1.Project create.
2.I applied patch.
3.parts 100% opaque Live2D model data is import.
4.Clipping masks are not good.

5.parts 0% opaque Animation application.
6.The parts flicker.

**Comment by sasakiSG** [comment]
http://blindfold.girly.jp/game/Live2D test3.zip
A button didn't move to the project a short while ago opaque. It's right here.
I think I find out that it flickers when clicking a button several times.

**Comment by sasakiSG** [comment]
I think a seen one can cut at the top and the bottom of the pupil about a clipping mask, and can check the white.

**Comment by andi-at-live2d-com** [comment]
Hey, thanks for the detailed explanation and the additional project. This might take some time, but please allow me to get back to you.

**Comment by itoh-at-live2d-com** [comment]
Hi.
I ran your project, imported your model data.
As you can see, it looks like work fine.
You can try to delete "Library" folder. Because, sometimes it makes problem.

![clipping](https://user-images.githubusercontent.com/28519948/27725902-5ab9f498-5db3-11e7-8211-35ca8fd6c27a.gif)

**Comment by sasakiSG** [comment]
I delete "Library" folder , a blink became normal.
Thank you very much.

But a flickering problem by opaque change is while being left.
Is it better to close this Issue and make a new Issue?

**Comment by itoh-at-live2d-com** [comment]
@sasakiSG 
Thank you for your cooperation!

And, before create new issue, can you try [this branch](https://github.com/Live2D/CubismUnityComponents/tree/develop)?
Flickering problem probably fixed.

**Comment by sasakiSG** [comment]
The brunch was applied and a library folder was deleted, but the flickers wasn't corrected.

**Comment by itoh-at-live2d-com** [comment]
@sasakiSG 
Thanks for trying.
Flickering problem isn't same this issue.
Could you create a new issue, and explain more details?

**Comment by sasakiSG** [comment]
Ok.

**Comment by itoh-at-live2d-com** [comment]
@sasakiSG 
I had overlooked problem, so I fixed again.
Masking calculating timing is fixed to  correct timing.
Sorry about  incompletely checking...
I'd appreciate very much if you try again.

**Comment by itoh-at-live2d-com** [comment]
@sasakiSG 
You can try [this branch](https://github.com/Live2D/CubismUnityComponents/tree/develop).
It is currently latest.

**Comment by sasakiSG** [comment]
It was moved.
It was seen, it's felt and it seems no problem.
Is R3 anything useless but different?
