### ISSUE TITLE
Opaque changed in the state to which brunch was applied, it flickers.

### ISSUE THREAD

**Issue by sasakiSG** [Live2D/CubismUnityComponents#5]
Brunch was applied to this project and a library folder was eliminated.

http://blindfold.girly.jp/game/Live2D test3.zip

When a button is clicked, the clarity by which the clarity of the blindfold is 0 and an eye will be 100.
Please click and confirm a button many times.
It flickers like this animation.

http://blindfold.girly.jp/game/flickers.zip

Flickering doesn't occur in the state to which SDK was just applied.
Only when applying brunch, it happens.

**Comment by itoh-at-live2d-com** [comment]
@sasakiSG 
Thanks for reporting.
I will check the behavior at latest branch.
Please wait just a little longer...

**Comment by itoh-at-live2d-com** [comment]
@sasakiSG 
Hi.
I solved this issue by fixing components code.
But, to completely fix, I have to supply latest NativeCore.
It will be supply in a few days.
Please wait a little while more.

**Comment by itoh-at-live2d-com** [comment]
@sasakiSG 
Sorry to have kept you waiting.
This issue is fixed at latest Sdk R3.
You can [download it](https://live2d.github.io/) and try out.
Latest Sdk has changed folder structures. Delete older before importing latest, I recommend.
Thank you!
