### ISSUE TITLE
iOS: libLive2DCubismCore missing full bitcode

### ISSUE THREAD

**Issue by Nyankoo** [Live2D/CubismUnityComponents#6]
When trying to build in XCode, the following error is thrown:

`- ld: bitcode bundle could not be generated because '/MyProject/Libraries/Live2D/Cubism/Plugins/iOS/libLive2DCubismCore.a(Live2DCubismCore.o)' was built without full bitcode.`

**Comment by itoh-at-live2d-com** [comment]
@Nyankoo 
Hi.
Thanks for reporting!

I will investigate it.
Please wait a while...

**Comment by itoh-at-live2d-com** [comment]
@Nyankoo 
As you said, this problem is caused by no bundling bitcode with CubismNativeCore.
We will consider to bundling bitcode.
A temporary measure, you can turn off "Enable Bitcode" option in XCode when archive the application.

**Comment by Nyankoo** [comment]
@itoh-at-live2d-com 
Thank you for looking into this!
Any ETA on when you will provide bitcode, as no bitcode support is very limiting to us?

**Comment by itoh-at-live2d-com** [comment]
@Nyankoo 
Yes.
We will provide bitcode ASAP if it has no problem.

**Comment by itoh-at-live2d-com** [comment]
@Nyankoo 
No bitcode support doesn't disturb your developing.
Because, it's a hint to compiler to optimize the program.
(I said "Yes" mean, I had understood that you said "This measure is limited to us.".)

**Comment by itoh-at-live2d-com** [comment]
@Nyankoo 
Hi.
We started providing SDK R5 including bitcode issue fixing.
Please [donwload](https://live2d.github.io/#unity) and try it out.
Sorry for late providing...
