### ISSUE TITLE
PS4: Live2D Cubism does not run on PS4

### ISSUE THREAD

**Issue by DiegoTorresBZS** [Live2D/CubismUnityComponents#8]
When I try to run an app on PS4 it shows me this message when it is loading:
"Unable to resolve pinvoke method 'Live2D.Cubism.Core.Unmanaged.CubismCoreDll:ReviveMocInPlace <intptr,uint>' Re-run with MONO_LOG_LEVEL=debug for more information.

**Comment by itoh-at-live2d-com** [comment]
@DiegoTorresBZS 
Hi.
To develop for PS4, you have to get NativeCore for PS4.
If you are PS4 developer, please contact Live2D via SIE.

**Comment by DiegoTorresBZS** [comment]
Hi, Thanks for the info. I have contacted Live2D via SIE confirming my PS4 developer status.
